#!/usr/bin/env bash


CONFIG_FILE=/etc/orchestrator.conf.json

cp /etc/orchestrator-docker.conf.json $CONFIG_FILE

sed -i 's/$DEBUG/'"${DEBUG:-false}"'/g' $CONFIG_FILE
sed -i 's/$ENABLE_SYS_LOG/'"${ENABLE_SYS_LOG:-false}"'/g' $CONFIG_FILE
sed -i 's/$MYSQL_ORCHESTRATOR_HOST/'"${MYSQL_ORCHESTRATOR_HOST:-mysql}"'/g' $CONFIG_FILE
sed -i 's/$MYSQL_ORCHESTRATOR_PORT/'"${MYSQL_ORCHESTRATOR_PORT:-3306}"'/g' $CONFIG_FILE
sed -i 's/$MYSQL_ORCHESTRATOR_DATABASE/'"${MYSQL_ORCHESTRATOR_DATABASE:-orchestrator}"'/g' $CONFIG_FILE
sed -i 's/$MYSQL_ORCHESTRATOR_USER/'"${MYSQL_ORCHESTRATOR_USER:-orchestrator}"'/g' $CONFIG_FILE
sed -i 's/$MYSQL_ORCHESTRATOR_PASSWORD/'"${MYSQL_ORCHESTRATOR_PASSWORD:-orchestrator_password}"'/g' $CONFIG_FILE
sed -i 's/$MYSQL_ORCHESTRATOR_USE_MUTUAL_TLS/'"${MYSQL_ORCHESTRATOR_USE_MUTUAL_TLS:-false}"'/g' $CONFIG_FILE

sed -i 's/$MYSQL_TOPOLOGY_PASSWORD/'"${MYSQL_TOPOLOGY_PASSWORD:-orc_client_password}"'/g' $CONFIG_FILE
sed -i 's/$MYSQL_TOPOLOGY_USER/'"${MYSQL_TOPOLOGY_USER:-orc_client_user}"'/g' $CONFIG_FILE
sed -i 's/$MYSQL_TOPOLOGY_USE_MUTUAL_TLS/'"${MYSQL_TOPOLOGY_USE_MUTUAL_TLS:-false}"'/g' $CONFIG_FILE

sed -i 's/$DISCOVER_BY_SHOW_SLAVE_HOSTS/'"${DISCOVER_BY_SHOW_SLAVE_HOSTS:-true}"'/g' $CONFIG_FILE
sed -i 's/$INSTANCE_POOL_SECONDS/'"${INSTANCE_POOL_SECONDS:-5}"'/g' $CONFIG_FILE
sed -i 's/$UNSEEN_INSTANCE_FORGET_HOURS/'"${UNSEEN_INSTANCE_FORGET_HOURS:-240}"'/g' $CONFIG_FILE
sed -i 's/$SNAPSHOT_TOPOLOGIES_INTERVAL_HOURS/'"${SNAPSHOT_TOPOLOGIES_INTERVAL_HOURS:-0}"'/g' $CONFIG_FILE
sed -i 's/$INSTANCE_BULK_OPERATIONS_WAIT_TIMEOUT_SECONDS/'"${INSTANCE_BULK_OPERATIONS_WAIT_TIMEOUT_SECONDS:-10}"'/g' $CONFIG_FILE
sed -i 's/$HOSTNAME_RESOLVED_METHOD/'"${HOSTNAME_RESOLVED_METHOD:-default}"'/g' $CONFIG_FILE
sed -i 's/$MYSQL_HOSTNAME_RESOLVE_METHOD/'"${MYSQL_HOSTNAME_RESOLVE_METHOD:-@@hostname}"'/g' $CONFIG_FILE
sed -i 's/$SKIP_BINLOG_SERVER_UNRESOLVE_CHECK/'"${SKIP_BINLOG_SERVER_UNRESOLVE_CHECK:-true}"'/g' $CONFIG_FILE
sed -i 's/$EXPIRY_HOSTNAME_RESOLVES_MINUTES/'"${EXPIRY_HOSTNAME_RESOLVES_MINUTES:-60}"'/g' $CONFIG_FILE
sed -i 's/$REJECT_HOSTNAME_RESOLVE_PATTERN/'"${REJECT_HOSTNAME_RESOLVE_PATTERN:-}"'/g' $CONFIG_FILE
sed -i 's/$REASONABLE_REPPLICATION_LAG_SECONDS/'"${REASONABLE_REPPLICATION_LAG_SECONDS:-10}"'/g' $CONFIG_FILE
sed -i 's/$PROBLEM_IGNORE_HOSTNAME_FILTERS/'"${PROBLEM_IGNORE_HOSTNAME_FILTERS:-[]}"'/g' $CONFIG_FILE
sed -i 's/$VERIFY_REPLICATION_FILTERS/'"${VERIFY_REPLICATION_FILTERS:-false}"'/g' $CONFIG_FILE
sed -i 's/$REASONABLE_MAINTENANCE_REPLICATION_LAG_SECONDS/'"${REASONABLE_MAINTENANCE_REPLICATION_LAG_SECONDS:-20}"'/g' $CONFIG_FILE
sed -i 's/$CANDIDATE_INSTANCE_EXPIRE_MIUNUTES/'"${CANDIDATE_INSTANCE_EXPIRE_MIUNUTES:-60}"'/g' $CONFIG_FILE
sed -i 's/$AUDIT_LOG_FILE/'"${AUDIT_LOG_FILE:-}"'/g' $CONFIG_FILE
sed -i 's/$AUDIT_TO_SYS_LOG/'"${AUDIT_TO_SYS_LOG:-false}"'/g' $CONFIG_FILE
sed -i 's/$REMOVE_TEXT_FROM_HOSTNAME_DISPLAY/'"${REMOVE_TEXT_FROM_HOSTNAME_DISPLAY:-.mydomain.com:3306}"'/g' $CONFIG_FILE
sed -i 's/$READ_ONLY/'"${READ_ONLY:-false}"'/g' $CONFIG_FILE
sed -i 's/$AUTHENTICATION_METHOD/'"${AUTHENTICATION_METHOD:-}"'/g' $CONFIG_FILE
sed -i 's/$HTTP_AUTH_USER/'"${HTTP_AUTH_USER:-}"'/g' $CONFIG_FILE
sed -i 's/$HTTP_AUTH_PASSWORD/'"${HTTP_AUTH_PASSWORD:-}"'/g' $CONFIG_FILE
sed -i 's/$AUTH_USER_HEADER/'"${AUTH_USER_HEADER:-}"'/g' $CONFIG_FILE
sed -i 's/$POWER_AUTH_USERS/'"${POWER_AUTH_USERS:-[\"*\"]}"'/g' $CONFIG_FILE
sed -i 's/$CLUSTER_NAME_TO_ALIAS/'"${CLUSTER_NAME_TO_ALIAS:-{\"127.0.0.1\": \"test suite\"}}"'/g' $CONFIG_FILE

exec /usr/local/orchestrator/orchestrator http